### ISSUE TITLE
Changing itunes account causing safe mode

### ISSUE THREAD

**Issue by ghost** [hbang/StoreAlert#7] opened 2017-07-18 03:52 UTC
In App Store, at the bottom of "Featured" , I logged out my Apple ID and Logged in another ID ( different country) . It alerted and I clicked yes. Crashed . I was sent to safe mode.

![img_0632](https://user-images.githubusercontent.com/12052610/28301196-670525c6-6bb7-11e7-92c5-50ba54978521.PNG)

Sorry for my English. I hope I made it clear. 

iOS 9.

**Comment by iAdam1n** [comment] 2017-07-18 08:15
Thanks for reporting. However, we don’t plan any updates to this tweak.

**Comment by ghost** [comment] 2017-07-18 09:25
why? I like this tweak.

If no update, would you recommend something similar ?

**Comment by iAdam1n** [comment] 2017-07-18 09:28
We currently have too many tweaks to manage and have to stop supporting some to focus on others. It doesn't seem that iOS 10 needs StoreAlert so it was one that we decided to not update again. I don't know of anything similar.

**Comment by kirb** [comment] 2017-07-18 11:07
Closing as duplicate of #5.

**Closed as completed by kirb** 2017-07-18 11:07 UTC
Labels: bug

**Comment by ghost** [comment] 2017-07-26 01:59
I found one similar . NoAppStoreRedirect
